let a = Number(prompt("Введите первое число: "))
let b = Number(prompt("Введите второе число: "))
alert(a + b)
alert(a - b)
alert(a * b)
alert(a / b)
alert(a ** b)
let numberOne = 8
alert(" 8 * 1 = " + numberOne * 1)
alert(" 8 * 2 = " + numberOne * 2)
alert(" 8 * 3 = " + numberOne * 3)
alert(" 8 * 4 = " + numberOne * 4)
alert(" 8 * 5 = " + numberOne * 5)
alert(" 8 * 6 = " + numberOne * 6)
alert(" 8 * 7 = " + numberOne * 7)
alert(" 8 * 8 = " + numberOne * 8)
alert(" 8 * 9 = " + numberOne * 9)
alert(" 8 * 10 = " + numberOne * 10)